spring.application.name=escenario-castores

spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/escenario_db_castores
spring.datasource.username=root
spring.datasource.password=@Lmmocon12

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate